# Generated by Django 6.0.6 on 2026-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_notes',
            field=models.TextField(blank=True, default='', help_text='Optional note from the vehicle owner explaining the decision.'),
        ),
    ]
