# Generated by Django 6.0.6 on 2026-07-04 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_admin_space', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null when is_admin_space=True (admin-owned folder).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_manager.mediafolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin_space', models.BooleanField(default=False)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('resource_type', models.CharField(default='image', max_length=20)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('secure_url', models.URLField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('raw', 'Raw')], default='image', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_manager.mediafolder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['owner', 'is_admin_space'], name='media_manag_owner_i_aafd03_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name', 'is_admin_space'), name='unique_folder_name_per_parent_per_space'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['owner', 'is_admin_space'], name='media_manag_owner_i_46efce_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['folder'], name='media_manag_folder__801da4_idx'),
        ),
    ]
