# Generated by Django 6.0.6 on 2026-07-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
        ('vehicles', '0003_vehicle_badge_vehicle_description_vehicle_image_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image_id',
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_links', to='media_manager.mediafile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('vehicle', 'media')},
            },
        ),
    ]
