# Generated by Django 6.0.6 on 2026-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_image_id_vehicleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('dirt-bike', 'Dirt-Bike'), ('suv', 'Suv'), ('electric', 'Electric'), ('scooter', 'Scooter')], max_length=20),
        ),
    ]
