# Generated by Django 6.0.6 on 2026-08-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleFeature',
        ),
    ]
