# Generated by Django 6.0.6 on 2026-08-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_delete_vehiclefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually mark this vehicle as featured on the public homepage.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
    ]
